# Copyright (c) 2025 Ainekko, Co.
# SPDX-License-Identifier: Apache-2.0

include(ExternalProject)
include(GoogleTest)

# System dependencies
find_package(deviceLayer REQUIRED)
find_package(sw-sysemu REQUIRED)

# Esperanto dependencies
find_package(EsperantoBootLoader)
find_package(EsperantoDeviceMinionRuntime)
find_package(EsperantoTestKernels)

find_package(gflags REQUIRED)


set(COMMON_DIR ${CMAKE_CURRENT_SOURCE_DIR}/common)
# Helper function to build a test binary
#
# Args
# NAME : binary name of the test
# SOURCES : list of source files
macro(build_test_binary)
    cmake_parse_arguments(TEST
        ""
        "TARGET;"
        "SOURCES;"
        ${ARGN}
    )

    add_executable(${TEST_TARGET} ${TEST_SOURCES})

    # We need PRIVATE include dirs
    get_target_property(ETRT_INCLUDE_DIRS etrt INCLUDE_DIRECTORIES)

    target_include_directories(${TEST_TARGET}
        PUBLIC
            ${ETRT_INCLUDE_DIRS}
        PRIVATE
            ${COMMON_DIR}
            ${PROJECT_SOURCE_DIR}/tests
    )

    target_link_libraries(${TEST_TARGET}
        PRIVATE
            easy_profiler
            runtime::test_utils
            runtime::etrt
            cereal::cereal
            gflags::gflags
            deviceLayer::deviceLayer
            sw-sysemu::sw-sysemu
            GTest::gtest            
            GTest::gmock
	    $<$<AND:$<CXX_COMPILER_ID:GNU>,$<VERSION_LESS:$<CXX_COMPILER_VERSION>,9.0.0>>:stdc++fs>
    )
    target_compile_definitions(${TEST_TARGET} 
        PRIVATE
          $<$<BOOL:${DISABLE_EASY_PROFILER}>: DISABLE_EASY_PROFILER>
    )    
    
    
    target_set_project_warnings(${TEST_TARGET})
    target_add_sanitizers(${TEST_TARGET})
endmacro()

## Helper function for creating the different test binary targets
## Args:
##  TEST_INFO: takes a list of string where the string a column (":") separated arguments
##     to emulate tuples where the first element of the tuple is the test source file
##     and the send element is any additional test arguments
##  TEST_LABEL String with the list of labels to apply to the test
function(create_test_targets TEST_LIST TEST_PROPERTIES PREFIX_TARGET_NAME)
  foreach(TEST_INFO ${TEST_LIST})
    string(REPLACE ":" ";" TMP_LIST ${TEST_INFO})
    list(GET TMP_LIST 0 TEST_FILE)
    
    message("Test source: " ${TEST_FILE})
    list(GET TMP_LIST 1 TEST_ARGS)
    # Remove the quotes from the string that we have passed otherwise they
    # survice in the invocation of gtest and result in incorrect argument parsing
    string(REPLACE "\"" "" TEST_ARGS ${TEST_ARGS})
    # Convert the string into a cmake list (";" separated) this will result in the2
    # argument list looking like --arg1=val1;--arg2=val2 etc
    # When passed to gtest_discover_tests in EXTRA_ARGS this will result in generating
    # "--arg1=val1"  "--arg2=val2"  that is the correct way to escape the arguments.
    string(REPLACE " " ";" TEST_ARGS "${TEST_ARGS}")
    # message("Test args: " ${TEST_ARGS})
    get_filename_component(TEST_TARGET ${TEST_FILE} NAME_WE)
    set(TEST_TARGET "${PREFIX_TARGET_NAME}${TEST_TARGET}")
    build_test_binary(
      TARGET ${TEST_TARGET}
      SOURCES ${TEST_FILE}
      )

    gtest_discover_tests(${TEST_PREFIX} ${TEST_TARGET}
      EXTRA_ARGS ${TEST_ARGS}
      TEST_PREFIX runtime:${PREFIX_TARGET_NAME}
      PROPERTIES ${TEST_PROPERTIES}
      TEST_LIST DISCOVERED_TESTS
      DISCOVERY_TIMEOUT 20
      )
    
    install(TARGETS ${TEST_TARGET}
      RUNTIME DESTINATION ${CMAKE_INSTALL_BINDIR}
      )
  endforeach(TEST_INFO)
endfunction()

if (EsperantoBootLoader_FOUND)
    get_property(BOOTROM_TRAMPOLINE_TO_BL2_ELF TARGET EsperantoBootLoader::BootromTrampolineToBL2.elf PROPERTY LOCATION)
    get_property(BL2_ELF TARGET EsperantoBootLoader::ServiceProcessorBL2_fast-boot.elf PROPERTY LOCATION)
endif()
if (EsperantoDeviceMinionRuntime_FOUND)
    get_property(MASTER_MINION_ELF TARGET EsperantoDeviceMinionRuntime::MasterMinion.elf PROPERTY LOCATION)
    get_property(MACHINE_MINION_ELF TARGET EsperantoDeviceMinionRuntime::MachineMinion.elf PROPERTY LOCATION)
    get_property(WORKER_MINION_ELF TARGET EsperantoDeviceMinionRuntime::WorkerMinion.elf PROPERTY LOCATION)
endif()

if (EsperantoTestKernels_FOUND)
    message(STATUS "EsperantoTestKernels FOUND, setting KERNELS_DIR from install location")
    set(KERNELS_DIR "${ESPERANTO_TEST_KERNELS_LIB_DIR}/esperanto-fw/kernels")
    message(STATUS "KERNELS_DIR: ${KERNELS_DIR}")
else()
    message(STATUS "EsperantoTestKernels NOT FOUND, setting KERNELS_DIR from PROJECT_SOURCE_DIR.")
    set(KERNELS_DIR "${PROJECT_SOURCE_DIR}/esperanto-test-kernels/lib/esperanto-fw/kernels")
    message(STATUS "KERNELS_DIR: ${KERNELS_DIR}")
endif()

include_directories(${CMAKE_CURRENT_BINARY_DIR})

add_subdirectory(common)
add_subdirectory(unit-tests)
add_subdirectory(integration-tests)
add_subdirectory(stress-tests)
if(BUILD_TOOLS)
  add_subdirectory(tools)
endif()
